services:
  kafka_broker:
    image: apache/kafka:latest
    container_name: kafka_broker
    ports:
      - "9094:9094" # external/host access
    environment:
      # KRaft mode (no Zookeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_broker:9093

      # Listeners
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092, EXTERNAL://0.0.0.0:9094, CONTROLLER://0.0.0.0:9093

      # Advertised listeners for different clients:
      # - Docker containers: kafka_broker:9092
      # - Host machine: localhost:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_broker:9092, EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT, CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Required replication settings for a single broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - n8n_net
        #- host_net

networks:
  n8n_net:
    name: n8n_network
    external:
      true
      #host_net:
      #driver: bridge

volumes:
  kafka_data:
