
version: "3.9"

services:

  redis:
    image: redis:7
    container_name: redis_db
    ports:
      - "6379:6379"
        # networks:
        # - app-network

  logic:
    build: ./logic
    container_name: business_logic
    ports:
      - "8000:8000"
    depends_on:
      - redis
        # networks:
        # - app-network

  frontend:
    build: ./frontend
    container_name: ui_server
    ports:
      - "9999:9999"
    depends_on:
      - logic
        # networks:
        # - app-network

        # networks:
        # app-network:
        # driver: bridge
